reskin glossing for TPEN3 -variables, filenames
CenterForDigitalHumanities/TPEN-Users pull request #17
Opened 2024-03-15 16:47 UTC by jsvoo

I changed all insatnces of gloss, glossing, Gloss, GLOSSING with Tpen in a case-sensitive manner (tpen for gloss, Tpen for Gloss, TPEN for GLOSS...).

<img width="195" alt="image" src="https://github.com/CenterForDigitalHumanities/Glossing-Users/assets/111019083/7f5bc25c-11f3-40ea-a9ab-3030575365df">

changed ROLE_CONTRIBUTOR_ID and ROLE_MANAGER_ID to ROLE_ADMIN_ID and ROLE_INACTIVE_ID in /routes/manage-api.js to start the app. further changes may be required especially with the current roleNames (manager, contributor, public)

2024-03-19 18:17 UTC, thehabes requested changes
### Logged in as an admin
I see myself in the users list.  My only role is 'tpen_user_admin'.  However, the badge notes me as "Public" even though I am an admin and do not have the public role.
![image](https://github.com/CenterForDigitalHumanities/TPEN-Users/assets/3287006/b682f9d5-23c3-49a3-b6e2-3a4977153671)

I am able to give myself a public or inactive role.  However, selecting this role removes my admin role.  The admin role should never be set or unset through this interface.

I see other admins in the list.  In particular, cubap.  cubap only has the role `tpen_user_admin`.  However, the interface notes him as "Public"
![image](https://github.com/CenterForDigitalHumanities/TPEN-Users/assets/3287006/e062b0f6-9ae5-403c-b033-7f65c7a11724)

When I select 'Public' to give cubap the `tpen_user_public` role, nothing happens.  I have to select "inactive" then "public" to make him public.  This might be an edge case you don't need to account for, just noting it.

When I successfully change cubap's role to "Public" his user no longer has the admin role.   The admin role should never be set or unset through this interface. 

I see the other users in list.  Joseph Grone is a public user, but his badge says undefined.
![image](https://github.com/CenterForDigitalHumanities/TPEN-Users/assets/3287006/90f3eb14-6447-4e4f-8e08-eb9e9eda8bbd)

### Logged in as a non-admin
I see my profile, but the styling needs a little work.  It is hard to read and understand.  It notes all my RERUM User ecosystem roles instead of just my role for TPEN.
![image](https://github.com/CenterForDigitalHumanities/TPEN-Users/assets/3287006/aecdfd45-39d5-4bfc-b55c-b05dcd53e444)

2024-03-19 21:17 UTC, cubap reviewed
I'm half done. I need to pull up. It looks good so far in the code. I won't own a review here since Bryan will be going through it with you, but I will check back in later.

2024-03-19 21:17 UTC, cubap commented on .github/workflows/cd.yaml
> +          pm2 start -i max bin/tpen_users.js
@thehabes has the knowledge. Changes to indents can be trouble, but this'll be tested.

2024-03-19 21:17 UTC, cubap commented on public/logout.html
> +    <p>This page will log you out of TPEN Matthew.</p>
Oops. Find and Replace didn't get it all here.

2024-03-19 21:17 UTC, cubap commented on public/profile.html
This page will probably land out of scope but changing names on it is fine.

2024-03-19 21:17 UTC, cubap commented on public/profile.html
> +                    TPEN Library &amp; Archive Users&nbsp;
Looks like this is wrong before and after :)

2024-03-19 21:17 UTC, cubap commented on public/script/heartbeat.js
> +    redirectUri: TPEN_REDIRECT,
@thehabes I assume has talked about this value.

2024-03-19 21:17 UTC, cubap commented on public/script/manage.js
> +        if (user?.role?.toLowerCase() !== "admin")
This removal of admin isn't needed because of its exclusion in `ROLES` above

2024-03-19 21:17 UTC, cubap commented on public/script/manage.js
> +        //This presumes they will only have one tpen role here.  Make sure getAllUsers() accounts for that.
"one role _here_" means once admin is removed, so it is still true

2024-03-19 23:37 UTC, jsvoo commented on public/logout.html
> +    <p>This page will log you out of TPEN Matthew.</p>
Mathew taken out.

2024-03-19 23:41 UTC, jsvoo commented on public/profile.html
> +                    TPEN Library &amp; Archive Users&nbsp;
resolved. I'm actually surprised this is still here. It was resolved in a later commit

2024-03-19 23:43 UTC, jsvoo commented on public/script/heartbeat.js
> +    redirectUri: TPEN_REDIRECT,
mmm, I'm sorry I can't recall that. if he did, I probably missed it and still need some clarification, please.

2024-03-19 23:43 UTC, jsvoo commented on public/script/manage.js
> +        if (user?.role?.toLowerCase() !== "admin")
resolved

2024-03-19 23:48 UTC, jsvoo commented on public/script/manage.js
> +        //This presumes they will only have one tpen role here.  Make sure getAllUsers() accounts for that.
it appears it meant that "one role here" indicated that each user returned by "getAllUser()" has only one role in their object which comes in the form of `{key:value, key:value, role:"public", key:value}`.

2024-03-21 14:51 UTC, jsvoo commented
Fixed all comments on user roles, admin and non-admin interfaces, display of users with their roles and role assignment

2024-03-22 02:39 UTC, thehabes requested changes
Good work, just some clean up things to do to get this through.

I made some new issues related to some of the inline comments I made.  I think there are some optimizations to do later down the road that we don't need to do in the scope of this PR.

2024-03-22 02:39 UTC, thehabes commented on routes/manage-api.js
> +            // get users in groups according to roles, attach role tag to user object, merge roles of users that appear in multiple groups
Though this works, I have a hard time believing this is the most optimized way to do this.  What we really want is somewhere in https://auth0.github.io/node-auth0/classes/management.UsersManager.html#getAll

What we want is
```
Get all users whose app.metadata contains "tpen".  Include their metadata and roles.
```
We will mark this as an optimization issue outside the scope of this PR.  We should look into using the most recent auth0 package and management client when we refactor this to use `import` instead of `require` (in favor of ES6 modules).  This can be tracked via #20

2024-03-22 02:39 UTC, thehabes commented on public/profile.html
Major improvements here are outside the scope of this PR.  However, the improvements you have done to make it more user friendly are much appreciated and will be accepted.

2024-03-22 02:39 UTC, thehabes commented on public/script/manage.js
> +  return await fetch("/tpen-users/manage/getAllUsers", {
You do not need this `await`.

2024-03-22 02:39 UTC, thehabes commented on public/script/manage.js
> +    },
remove this comma

2024-03-22 02:39 UTC, thehabes commented on public/script/manage.js
> +    .then((resp) => {
I think this is a linter or prettifier thing.  You do not need this `( )` but it doesn't break anything.

2024-03-22 02:39 UTC, thehabes commented on routes/manage-api.js
> +  process.env.ROLE_PUBLIC_ID,
get rid of extra comma

2024-03-22 02:39 UTC, thehabes commented on routes/manage-api.js
> +  clientId: process.env.CLIENTID,
get rid of extra comma

2024-03-22 16:11 UTC, thehabes approved these changes

2024-03-22 16:11 UTC, merged